version: '3.4'

services:

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - 9200:9200
