version: '3.4'

services:

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: conductor
      MYSQL_USER: conductor
      MYSQL_PASSWORD: password
    volumes:
      - type: volume
        source: conductor_mysql
        target: /var/lib/mysql
    networks:
      - internal
    ports:
      - 3306:3306

  elasticsearch:
    image: elasticsearch:5.6-alpine
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  conductor_mysql:

networks:
  internal:
